#cluster_slurm.yaml  fastq_to_bam_paired.snakefile
#samuel ahunos
#Template made October 18th, 2019
#Ha Lab: Fred Hutchinson Cancer Research Center

__default__:
    #partition: general #bsub is default
    time: 1:00
    mem: "rusage[mem=1000]"
    nTasks: 16
    jobName: {rule}
    output: logs/cluster/{rule}.%J.out
    errorFile: logs/cluster/{rule}.%J.err

# nameOfRule:
#     time: "48:0:0"
#     mem: 12G
#     ncpus: 4